### ISSUE TITLE
what's the need for this library? libxmljs2 validates by xsd itself

### ISSUE THREAD

**Issue by freerider7777** [cdegalitt/libxmljs2-xsd#14]

**Comment by cdegalitt** [comment]
I wasn't aware of that ! Thanks for noticing !

**Comment by cdegalitt** [comment]
Indeed, there is some documentation on how to perform validation against an XSD schema in libxmljs2's Wiki : https://github.com/marudor/libxmljs2/wiki#validating-against-xsd-schema

Therefore, this library (libxmljs2-xsd) could be made obsolete, deprecated and go unmaintained, which would be a good thing :)

**Comment by rpastro** [comment]
@cdegalitt   Does libxmljs2 support parsing the xsd from local files like libxmljs2-xsd?

**Comment by cdegalitt** [comment]
I think so, since you provide a string !

Please take a look at their sample code in the aforementionned Wiki :
var xsd = '<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"><xs:element name="comment"><xs:complexType><xs:all><xs:element name="author" ...';
var xsdDoc = libxml.parseXml(xsd);

**Comment by rpastro** [comment]
@cdegalitt   I think the issue with libxmljs2 was that it did not support loading an XSD that contains references to other schemas using a relative path. For instance:
```
	<xsd:import namespace="urn:nena:xml:ns:LoggingDataTypes:2.0" schemaLocation="../../extension/2.0/LoggingDataTypes.xsd"/>
	<xsd:import namespace="http://release.niem.gov/niem/appinfo/3.0/" schemaLocation="../../niem/appinfo/3.0/appinfo.xsd"/>
	<xsd:import namespace="http://release.niem.gov/niem/structures/3.0/" schemaLocation="../../niem/structures/3.0/structures.xsd"/>
```

**Comment by rpastro** [comment]
I recall that we looked into using libxmljs2 for the schema validation initially and we weren't able. I think it had to do with the relative paths.

**Comment by cdegalitt** [comment]
You're right ! That was the problem that libxmljs2-xsd was made to solve.
It would be worth checking if this is still the case, and if so, whether this could be integrated into libxmljs2.

**Comment by cdegalitt** [comment]
So this is the clear answer to OP

- libxmljs2 can validate XML against XSDs that are publicly accessible by URLs
- libxmljs2-xsd can validate XML against XSDs that links to local XSD schema files, based on a relative path on the local filesystem.

**Comment by rpastro** [comment]
@cdegalitt   It would be great to document exactly what you mentioned above in the README.
