### ISSUE TITLE
Xsd 1.1 support

### ISSUE THREAD

**Issue by ManosAgelidis** [cdegalitt/libxmljs2-xsd#6]
Hi, 

I have a question, is there a plan to start supporting xsd1.1 schemas? I am trying to use the parseFile function on a schema that has an element inside an xsd:all tag that has maxOccurs="unbounded" which is permitted in xsd1.1 but not in xsd1.0 . I suppose that the library currently supports only xsd1.0, or is this assumption wrong? For clarifiication in my schema there is an entry like:

<xsd:all>
       <xsd:element name="configuration" type="ConfFile" minOccurs="0" maxOccurs="unbounded">
        <xsd:annotation>
          <xsd:documentation>An experiment may have multiple configuration entries. Despite configuration entries can be specified in anywhere in the ExD element, they must appear together.</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
</xsd:all>

**Comment by cdegalitt** [comment]
Unfortunately, it is very hard to find a javascript or native library that performs XSD 1.1 schema validation.
I did read that xerces-java does the job, but as far as I understood, it seems that xerces-c does not support XSD 1.1.
As I do not have time to work on this, i updated the README to clearly state the lib only supports XSD 1.0.
If you have time and patience to integrate an XSD 1.1 validator, please get in touch or submit a PR :)

**Comment by ManosAgelidis** [comment]
Noted, thanks a lot!

**Comment by cdegalitt** [comment]
Closing because not planned for this library, and too complex to implement.
The readme now includes a section explaining this is out of scope, sorry
