### ISSUE TITLE
AWS lambda webpack bundling issue - “Could not find module root given file: \”/var/task/index.js\"

### ISSUE THREAD

**Issue by Leigh-M** [cdegalitt/libxmljs2-xsd#7]
I have an AWS lambda function that runs fine until I include this lib - then throws with full error:

```
    "errorMessage": "Could not find module root given file: \"/var/task/index.js\". Do you have a `package.json` file? ",
    "stack": [
        "Error: Could not find module root given file: \"/var/task/index.js\". Do you have a `package.json` file? ",
        "    at Function.getRoot (/var/task/index.js:5286:13)",
        "    at bindings (/var/task/index.js:5157:32)",
        "    at Object../node_modules/libxmljs2/lib/bindings.js (/var/task/index.js:7094:92)",
        "    at __webpack_require__ (/var/task/index.js:16311:42)",
        "    at Object../node_modules/libxmljs2/index.js (/var/task/index.js:7042:18)",
        "    at __webpack_require__ (/var/task/index.js:16311:42)",
        "    at Object../node_modules/libxmljs2-xsd/index.js (/var/task/index.js:6954:16)",
        "    at __webpack_require__ (/var/task/index.js:16311:42)",
        "    at Object../src/validateXML.js (/var/task/index.js:16099:13)",
        "    at __webpack_require__ (/var/task/index.js:16311:42)"
```
It is being bundled via webpack so possible it is bundling that is the issue - although no other modules appear to have this issue. It looks like it is calling libxmljs2 and not able to resolve from the package.json. Any thoughts much appreciated. Thanks in advance

**Comment by Leigh-M** [comment]
Just an addendum to this, I actually managed to get this running (this is not clean and it still needs resolving for anyone else running into this). It appears that it needs any package.json just containing an empty {} is fine, in the /dist folder and 2 binaries from node modules to run, in full:

My webpacked /dist folder now looks like:

```
/dist
   /someHandler
      index.js
   /anotherHandler
      /build
         node-libxml-xsd.node
         xmljs.node
      index.js
      package.json
```

the node-libxml-xsd.node binary was in node_modules/libxmljs2-xsd/build and xmljs.node was in node_modules/build/Release

So it does now run with the work-around solution, but I am not certain why this module is not being bundled correctly by webpack - my lack of knowledge around node_modules & webpack bundling here. Thanks

**Comment by cdegalitt** [comment]
This is a webpack configuration issue,. 
Are you trying to use this library in a backend or a frontend app ?

**Comment by cdegalitt** [comment]
> the node-libxml-xsd.node binary was in node_modules/libxmljs2-xsd/build and xmljs.node was in node_modules/build/Release  

It's curious that xmljs.node was produced within node_modules/build/Release, instead of node_modules/libxmljs2/build/Release
Interesting... The problem is probably with libxmljs2, though.

**Comment by raffihsieh** [comment]
I am also experiencing this problem, however I am not using the libxmljs2-xsd package, but just the libxmljs2 package.

**Comment by raffihsieh** [comment]
@Leigh-M  how did you modify your webpack.config.js to include those files?

**Comment by raffihsieh** [comment]
after trying out the hack solution above, my lambda still gives me an error:

```
2021-10-14T18:40:10.359Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "/var/task/build/xmljs.node: invalid ELF header",
    "stack": [
        "Error: /var/task/build/xmljs.node: invalid ELF header",
        "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)",
        "    at Module.load (internal/modules/cjs/loader.js:937:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
        "    at Module.require (internal/modules/cjs/loader.js:961:19)",
        "    at require (internal/modules/cjs/helpers.js:92:18)",
        "    at bindings (/var/task/lambda.js:3616:48)",
        "    at Object../node_modules/libxmljs2/lib/bindings.js (/var/task/lambda.js:82405:92)",
        "    at __webpack_require__ (/var/task/lambda.js:202540:42)",
        "    at Object../node_modules/libxmljs2/index.js (/var/task/lambda.js:82353:18)",
        "    at __webpack_require__ (/var/task/lambda.js:202540:42)"
    ]
}
```
a quick search brings us here: https://aws.amazon.com/blogs/compute/nodejs-packages-in-lambda/ which pretty much says that native libraries need to be compiled on the amazon linux EC2 image to work properly.

**Comment by Leigh-M** [comment]
@raffihsieh just checking the work-around setup..  If you just add an empty package.json in your /dist/someHandler folder (so it's sat next to your index.js) then run your lambda, you should see: 

```
errorType": "Error",
  "errorMessage": "Could not locate the bindings file. Tried:\n → /var/task/build/xmljs.node\n → /var/task/build/Debug/xmljs.node\n → /var/task/build/Release/xmljs.node\n → /var/task/out/Debug/xmljs.node\n → /var/task/Debug/xmljs.node\n → /var/task/out/Release/xmljs.node\n → /var/task/Release/xmljs.node\n → /var/task/build/default/xmljs.node\n → /var/task/compiled/12.22.4/linux/x64/xmljs.node\n → /var/task/addon-build/release/install-root/xmljs.node\n → /var/task/addon-build/debug/install-root/xmljs.node\n → /var/task/addon-build/default/install-root/xmljs.node\n → /var/task/lib/binding/node-v72-linux-x64/xmljs.node",
  "trace": [
    "Error: Could not locate the bindings file. Tried:",
    " → /var/task/build/xmljs.node",
```

So hence (for me) it was looking for: build/xmljs.node and it wasn't present..  hence, create the /build folder with the xmljs.node & node-libxml-xsd.node files in there - and it should run?  (Or does for me ;) )

If that works manually, I just wrote a shell script which I run as part of the build stage to automate the create and copy of those required libs - so in my package.json I have:
    `"build": "node scripts/bundle && bash scripts/buildLibxmlDependencies.sh`

buildLibxmlDependencies.sh:
```
echo "{}" > dist/someLambdaHandler/package.json
mkdir dist/someLambdaHandler/build
cp node_modules/libxmljs2-xsd/build/Release/node-libxml-xsd.node dist/someLambdaHandler/build
cp node_modules/libxmljs2/build/Release/xmljs.node dist/someLambdaHandler/build
```

Bit clunky but works fine in the short term - until someone fixes this ;)

**Comment by Leigh-M** [comment]
@cdegalitt - some more info, I have lambdas that use  parseStringPromise & Builder successfully, ie:

`const { parseStringPromise: parseXML, Builder } = require('xml2js');`

I can parseXML and build XML from objects no issues.

It doesn't require the /build folder with .node files or empty package.json:
   /yourLambdaHandler
      /build
         node-libxml-xsd.node
         xmljs.node
      index.js
      package.json

in those lambdas. It's just when I need to validate my XML, like:

```
const xsd = require('libxmljs2-xsd');
const schemaString = require('./yourXMLSchema');

const validateXML = someXMLString => {
    const schema = xsd.parse(schemaString);

    return schema.validate(someXMLString);
};

Afraid it seems to be specific to the 'libxmljs2-xsd' - or how it wraps libxmljs2
